"""Add cashier_id to open_till

Revision ID: b9c2e47231e1
Revises: be4fa58c3301
Create Date: 2025-01-02 23:22:07.999506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c2e47231e1'
down_revision = 'be4fa58c3301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_till', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cashier_id', type_='foreignkey')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('open_till', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_cashier_id', 'cashiers', ['cashier_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
