"""Initial migration.

Revision ID: be4fa58c3301
Revises: 
Create Date: 2024-10-24 00:05:13.930505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4fa58c3301'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.drop_constraint('managers_passcode_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.create_unique_constraint('managers_passcode_key', ['passcode'])

    # ### end Alembic commands ###
